# Generated by Django 5.2.8 on 2026-03-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investortransaction',
            name='type',
            field=models.CharField(choices=[('injection', 'Injection'), ('contribution', 'Contribution'), ('withdrawal', 'Withdrawal')], max_length=20),
        ),
    ]
