# Generated by Django 5.2.8 on 2026-03-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0002_alter_investortransaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='supplier_name',
            field=models.CharField(default='System', max_length=255),
        ),
    ]
