# Generated by Django 5.2.8 on 2026-06-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0004_banktransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransaction',
            name='date',
            field=models.DateField(),
        ),
    ]
